extends Node

# BLOCK SCENES
const BLOCKS: Dictionary = {
	"collector": "uid://6ruwp8q5nkxq",
	"crank": "uid://jom8h5cpaflf",
	"crossover": "uid://c42vopbjwddp3",
	"door": "uid://mf5yba3ubneh",
	"funnel": "uid://b6qdfofwdxc10",
	"funneldown": "uid://b72225wfa4juw",
	"funnelup": "uid://clb6s0nsyv5ek",
	"launcher": "uid://tuon10r6efg2",
	"organ": "uid://bjm5adujsb37w",
	"pipe": "uid://xqpuc0phpng0",
	"tubes": "uid://cuye5ggmiahfj",
	"valve": "uid://lb5n2nfdxpdm",
	"vent": "uid://biwhwmhbdhote",
	"engine": "uid://boipkeqb0lll6",
	"revolver": "uid://c7mag2f0lv3ut",
	"stomper": "uid://muqtkakm3gkd",
	"gear": "uid://di7l1oltbkins",
	"bellows": "uid://glaw4j7finwb",
	"bellowsriser": "uid://b8gbot26acxqh",
	"lamp": "uid://uth4dxpipy63",
	"piston": "uid://36rwld7vohrd",
	"pistonlifter": "uid://c6enr8nrs6u1e",
	"scrambler": "uid://si3acpt58wxq",
	"spike": "uid://doydskiq4qofp",
}

const STEAM_SCENE: PackedScene = preload("uid://btffcbbs7ojqg");
const BORDER_SCENE: PackedScene = preload("uid://ei4ickdodkmx");

const PIPE_TEXTURES: Array[Texture2D] = [
	preload("res://block sprites/Conductor/pipes/pipe_base.png"),
	preload("res://block sprites/Conductor/pipes/pipe_down.png"),
	preload("res://block sprites/Conductor/pipes/pipe_up.png"),
	preload("res://block sprites/Conductor/pipes/pipe_vertical.png"),
	preload("res://block sprites/Conductor/pipes/pipe_right.png"),
	preload("res://block sprites/Conductor/pipes/pipe_corner_DR.png"),
	preload("res://block sprites/Conductor/pipes/pipe_corner_UR.png"),
	preload("res://block sprites/Conductor/pipes/pipe_T_left.png"),
	preload("res://block sprites/Conductor/pipes/pipe_left.png"),
	preload("res://block sprites/Conductor/pipes/pipe_corner_DL.png"),
	preload("res://block sprites/Conductor/pipes/pipe_corner_UL.png"),
	preload("res://block sprites/Conductor/pipes/pipe_T_right.png"),
	preload("res://block sprites/Conductor/pipes/pipe_horizontal.png"),
	preload("res://block sprites/Conductor/pipes/pipe_T_up.png"),
	preload("res://block sprites/Conductor/pipes/pipe_T_down.png"),
	preload("res://block sprites/Conductor/pipes/pipe_cross.png"),
]

const BORDER_TEXTURES: Dictionary = {
	0: preload("res://block sprites/Border/border_base.png"),
	255: preload("res://block sprites/Border/border_none.png"),
	2: preload("res://block sprites/Border/End/border_end_down.png"),
	4: preload("res://block sprites/Border/End/border_end_left.png"),
	8: preload("res://block sprites/Border/End/border_end_right.png"),
	1: preload("res://block sprites/Border/End/border_end_up.png"),
	12: preload("res://block sprites/Border/Straight/border_straight_horizontal.png"),
	3: preload("res://block sprites/Border/Straight/border_straight_vertical.png"),
	9: preload("res://block sprites/Border/Corner/border_corner_DL.png"),
	9 + 32: preload("res://block sprites/Border/Corner/border_corner_DL-UR.png"),
	5: preload("res://block sprites/Border/Corner/border_corner_DR.png"),
	5 + 16: preload("res://block sprites/Border/Corner/border_corner_DR-UL.png"),
	10: preload("res://block sprites/Border/Corner/border_corner_UL.png"), 
	10 + 128: preload("res://block sprites/Border/Corner/border_corner_UL-DR.png"),
	6: preload("res://block sprites/Border/Corner/border_corner_UR.png"),
	6 + 64: preload("res://block sprites/Border/Corner/border_corner_UR-DL.png"), 
	14:	preload("res://block sprites/Border/T/border_T_down.png"), 
	14 + 64: preload("res://block sprites/Border/T/border_T_down-DL.png"), 
	14 + 128: preload("res://block sprites/Border/T/border_T_down-DR.png"), 
	14 + 64 + 128: preload("res://block sprites/Border/T/border_T_down-DL_DR.png"), 
	7: preload("res://block sprites/Border/T/border_T_left.png"), 
	7 + 16: preload("res://block sprites/Border/T/border_T_left-UL.png"), 
	7 + 64: preload("res://block sprites/Border/T/border_T_left-DL.png"), 
	7 + 64 + 16: preload("res://block sprites/Border/T/border_T_left-UL_DL.png"), 
	11: preload("res://block sprites/Border/T/border_T_right.png"), 
	11 + 32: preload("res://block sprites/Border/T/border_T_right-UR.png"), 
	11 + 128: preload("res://block sprites/Border/T/border_T_right-DR.png"), 
	11 + 32 + 128: preload("res://block sprites/Border/T/border_T_right-UR_DR.png"), 
	13: preload("res://block sprites/Border/T/border_T_up.png"), 
	13 + 16: preload("res://block sprites/Border/T/border_T_up-UL.png"),
	13 + 32: preload("res://block sprites/Border/T/border_T_up-UR.png"), 
	13 + 16 + 32: preload("res://block sprites/Border/T/border_T_up-UL_UR.png"), 
	15: preload("res://block sprites/Border/Cross/border_cross.png"),
	15 + 16: preload("res://block sprites/Border/Cross/border_cross-UL.png"), 
	15 + 32: preload("res://block sprites/Border/Cross/border_cross-UR.png"), 
	15 + 64: preload("res://block sprites/Border/Cross/border_cross-DL.png"), 
	15 + 128: preload("res://block sprites/Border/Cross/border_cross-DR.png"), 
	15 + 16 + 32: preload("res://block sprites/Border/Cross/border_cross-UL_UR.png"), 
	15 + 16 + 64: preload("res://block sprites/Border/Cross/border_cross-UL_DL.png"), 
	15 + 16 + 128: preload("res://block sprites/Border/Cross/border_cross-UL_DR.png"), 
	15 + 32 + 64: preload("res://block sprites/Border/Cross/border_cross-UR_DL.png"), 
	15 + 32 + 128: preload("res://block sprites/Border/Cross/border_cross-UR_DR.png"), 
	15 + 64 + 128: preload("res://block sprites/Border/Cross/border_cross-DL_DR.png"), 
	15 + 16 + 32 + 64: preload("res://block sprites/Border/Cross/border_cross-UL_UR_DL.png"), 
	15 + 16 + 32 + 128: preload("res://block sprites/Border/Cross/border_cross-UL_UR_DR.png"), 
	15 + 16 + 64 + 128: preload("res://block sprites/Border/Cross/border_cross-UL_DL_DR.png"),
	15 + 32 + 64 + 128: preload("res://block sprites/Border/Cross/border_cross-UR_DL_DR.png"),
}

#const BORDER_TEXTURES: Dictionary = {
	#0: preload("res://block sprites/Border/border_base.png"),
	#255: preload("res://block sprites/Border/border_none.png"),
	#Dir.UP: preload("res://block sprites/Border/End/border_end_up.png"),
	#Dir.DOWN: preload("res://block sprites/Border/End/border_end_down.png"),
	#Dir.LEFT: preload("res://block sprites/Border/End/border_end_left.png"),
	#Dir.RIGHT: preload("res://block sprites/Border/End/border_end_right.png"),
	#Dir.LEFT | Dir.RIGHT: preload("res://block sprites/Border/Straight/border_straight_horizontal.png"),
	#Dir.UP | Dir.DOWN: preload("res://block sprites/Border/Straight/border_straight_vertical.png"),
	#Dir.UP | Dir.RIGHT: preload("res://block sprites/Border/Corner/border_corner_DL.png"),
	#Dir.UP | Dir.RIGHT | Dir.UR: preload("res://block sprites/Border/Corner/border_corner_DL-UR.png"),
	#Dir.UP | Dir.LEFT: preload("res://block sprites/Border/Corner/border_corner_DR.png"),
	#Dir.UP | Dir.LEFT | Dir.UL: preload("res://block sprites/Border/Corner/border_corner_DR-UL.png"),
	#Dir.DOWN | Dir.RIGHT: preload("res://block sprites/Border/Corner/border_corner_UL.png"), 
	#Dir.DOWN | Dir.RIGHT | Dir.DR: preload("res://block sprites/Border/Corner/border_corner_UL-DR.png"),
	#Dir.DOWN | Dir.LEFT: preload("res://block sprites/Border/Corner/border_corner_UR.png"),
	#Dir.DOWN | Dir.LEFT | Dir.DL: preload("res://block sprites/Border/Corner/border_corner_UR-DL.png"), 
	#Dir.DOWN | Dir.LEFT | Dir.RIGHT: preload("res://block sprites/Border/T/border_T_down.png"), 
	#Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.DL: preload("res://block sprites/Border/T/border_T_down-DL.png"), 
	#Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.DR: preload("res://block sprites/Border/T/border_T_down-DR.png"), 
	#Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.DL | Dir.DR: preload("res://block sprites/Border/T/border_T_down-DL_DR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT: preload("res://block sprites/Border/T/border_T_left.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.UL: preload("res://block sprites/Border/T/border_T_left-UL.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.DL: preload("res://block sprites/Border/T/border_T_left-DL.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.UL | Dir.DL: preload("res://block sprites/Border/T/border_T_left-UL_DL.png"), 
	#Dir.UP | Dir.DOWN | Dir.RIGHT: preload("res://block sprites/Border/T/border_T_right.png"), 
	#Dir.UP | Dir.DOWN | Dir.RIGHT | Dir.UR: preload("res://block sprites/Border/T/border_T_right-UR.png"), 
	#Dir.UP | Dir.DOWN | Dir.RIGHT | Dir.DR: preload("res://block sprites/Border/T/border_T_right-DR.png"), 
	#Dir.UP | Dir.DOWN | Dir.RIGHT | Dir.UR | Dir.DR: preload("res://block sprites/Border/T/border_T_right-UR_DR.png"), 
	#Dir.UP | Dir.LEFT | Dir.RIGHT: preload("res://block sprites/Border/T/border_T_up.png"), 
	#Dir.UP | Dir.LEFT | Dir.RIGHT | Dir.UL: preload("res://block sprites/Border/T/border_T_up-UL.png"),
	#Dir.UP | Dir.LEFT | Dir.RIGHT | Dir.UR: preload("res://block sprites/Border/T/border_T_up-UR.png"), 
	#Dir.UP | Dir.LEFT | Dir.RIGHT | Dir.UL | Dir.UR: preload("res://block sprites/Border/T/border_T_up-UL_UR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT: preload("res://block sprites/Border/Cross/border_cross.png"),
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UL: preload("res://block sprites/Border/Cross/border_cross-UL.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UR: preload("res://block sprites/Border/Cross/border_cross-UR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.DL: preload("res://block sprites/Border/Cross/border_cross-DL.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.DR: preload("res://block sprites/Border/Cross/border_cross-DR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UL | Dir.UR: preload("res://block sprites/Border/Cross/border_cross-UL_UR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UL | Dir.DL: preload("res://block sprites/Border/Cross/border_cross-UL_DL.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UL | Dir.DR: preload("res://block sprites/Border/Cross/border_cross-UL_DR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UR | Dir.DL: preload("res://block sprites/Border/Cross/border_cross-UR_DL.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UR | Dir.DR: preload("res://block sprites/Border/Cross/border_cross-UR_DR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.DL | Dir.DR: preload("res://block sprites/Border/Cross/border_cross-DL_DR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UL | Dir.UR | Dir.DL: preload("res://block sprites/Border/Cross/border_cross-UL_UR_DL.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UL | Dir.UR | Dir.DR: preload("res://block sprites/Border/Cross/border_cross-UL_UR_DR.png"), 
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UL | Dir.DL | Dir.DR: preload("res://block sprites/Border/Cross/border_cross-UL_DL_DR.png"),
	#Dir.UP | Dir.DOWN | Dir.LEFT | Dir.RIGHT | Dir.UR | Dir.DL | Dir.DR: preload("res://block sprites/Border/Cross/border_cross-UR_DL_DR.png"),
#}
